Feat/custom s3 client
near/near-lake-framework-rs pull request #102
Opened 2024-04-14 23:23 UTC by morgsmccauley

2024-04-15 01:56 UTC, morgsmccauley commented on src/lib.rs
> +            &*lake_s3_client,
Dereference the `Box`, and pass a reference to the underlying trait object.

2024-04-15 01:57 UTC, morgsmccauley commented on src/s3_client.rs
> +}
Essentially some helpers to make these errors easier to work with

2024-04-15 01:59 UTC, morgsmccauley commented on src/types.rs
> +    pub fn s3_client<T: S3Client + 'static>(self, s3_client: T) -> Self {
Custom setter which allows passing `S3Client` directly, rather than requiring user to wrap in `Box`.

2024-04-15 02:00 UTC, morgsmccauley commented on src/types.rs
> -    AwsSmithyError {
`S3GetError`/`S3ListError` now contain both `AwsError` and `AwsSmithyError` as discussed in "Type Erasure".

2024-04-15 08:18 UTC, khorolets reviewed
Overall looks great! Thank you for improving the code base ❤️

I am going to try out this changes with some of the existing indexers to see the amount of changes required for the users to adopt it (mostly to figure out how painful it is around the error handling part). I will update you after that (ETA today-tomorrow)

2024-04-15 08:18 UTC, khorolets commented on src/s3_fetchers.rs
> +                            "Block #{:0>12} not found. Retrying in immediately...\n{:#?}",
```suggestion
                            "Block #{:0>12} not found. Retrying immediately...\n{:#?}",
```

2024-04-15 08:18 UTC, khorolets commented on src/s3_fetchers.rs
> +                            "Shard {} of block #{:0>12} not found. Retrying in immediately...\n{:#?}",
```suggestion
                            "Shard {} of block #{:0>12} not found. Retrying immediately...\n{:#?}",
```

2024-04-15 08:22 UTC, morgsmccauley commented
Thanks @khorolets! I already have a PR which integrates this in to QueryAPI, you can take a look [here](https://github.com/near/queryapi/pull/662/files#diff-004f24c0c8e5625132a226b9b790c1ec85496832541df4a713f401ef772bd3ce).

2024-04-16 04:57 UTC, morgsmccauley commented
@khorolets Implementation with cache: https://github.com/near/queryapi/pull/665

2024-04-16 07:23 UTC, khorolets requested changes
I have checked the code you've shared and tried this code out and have no objections to release it.

One thing that bothers me a bit is that it will break error handling for those who uses exposed methods from the library since the error have changed a bit.

@morgsmccauley may I ask you to bump the version and update the CHANGELOG.md? Thus I will be able to release the new version with your changes after merging this PR. Thank you!

2024-04-16 12:08 UTC, merged